#+options: toc:nil
* LI - backLIght changer
#+html: <img src="https://img.shields.io/badge/license-GPLv3-blue"><img src="https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg">
Light command is a small c program that adjusts the brightness of monitors. At
the moment, only built-in monitors work i.e. most laptop monitors. Why make such
a tiny program? There was a vacuum between gui application and shell scripts.
The author did not particularly enjoy =xbacklight= (specially it's dependence on a
xconfig file for the monitor in some cases, and the syntax is just stupid...
=-set=?).

LI seeks to correct this somewhat... but it's not developed for the masses --
just for me, so don't expect anything.

* Features
- Adjust brightness of built-in monitors (laptop monitors).
- Works on % of maxbrightness, not the arbitrary /sys/class/backlight... value fun.
- Micro codebase.

* Manual
** Downloading
*** git HTTPS
To get the latest version with git over HTTPS:
#+begin_src sh
git clone https://github.com/cafkafk/li.git
#+end_src
*** git SSH
To get the latest version with git over SSH:
#+begin_src sh
git clone git@github.com:cafkafk/li.git
#+end_src

** Building
To build simply run:
#+begin_src bash
$ make
#+end_src
** Installing
To install simply run:
#+begin_src bash
$ make install
#+end_src
** Uninstalling
To uninstall simply run:
#+begin_src bash
$ make uninstall
#+end_src
** Usage
To get help for =lc=
#+begin_src sh
$ lc --help
#+end_src
To set the target brightness (as an integer).
#+begin_src
# lc [int]
#+end_src

*Notice*: the brightness is a percentage, so 100 -> 100% brightness,
50 -> 50% brightness etc...

Further it must be in the interval (0;100].

** ROADMAP
- [-] built-in monitor support
- [ ] I2C support
- [ ] (unsure) multi-monitor
